// SIGN UP FORM
export const SIGNUP_CHANGE_USERNAME = 'SIGNUP_CHANGE_USERNAME'
export const SIGNUP_CHANGE_PASSWORD = 'SIGNUP_CHANGE_PASSWORD'
export const SIGNUP_CHANGE_PASSWORD_REPAET = 'SIGNUP_CHANGE_PASSWORD_REPAET'
export const SIGNUP_CHANGE_EMAIL = 'SIGNUP_CHANGE_EMAIL'
export const SIGNUP_CHANGE_GENDER = 'SIGNUP_CHANGE_GENDER'
export const SIGNUP_CHANGE_DATE_BIRTH = 'SIGNUP_CHANGE_DATE_BIRTH'

// SIGN IN FORM
export const SIGNIN_CHANGE_LOGIN = 'SIGNIN_CHANGE_LOGIN'
export const SIGNIN_CHANGE_PASSWORD = 'SIGNIN_CHANGE_PASSWORD'

// APP 
export const APP_CHANGE_LOADING_STATE = 'APP_CHANGE_LOADING_STATE'
export const APP_CHANGE_FORM_STATE = 'APP_CHANGE_FORM_STATE'
export const APP_CHANGE_FORM_LOADING_STATE = 'APP_CHANGE_FORM_LOADING_STATE'
export const APP_CHANGE_ERROR = 'APP_CHANGE_ERROR'
export const INITIALIZE_APP = 'INITIALIZE_APP'

// USER
export const USER_CHANGE_USERNAME = 'USER_CHANGE_USERNAME'
export const USER_CHANGE_AVATAR = 'USER_CHANGE_AVATAR'
export const USER_CHANGE_IS_AUTH = 'USER_CHANGE_IS_AUTH'
export const USER_CHANGE_ID = 'USER_CHANGE_ID'

// CHATS
export const CHATS_CHANGE_LIST = 'CHATS_CHANGE_LIST'
export const CHATS_CHANGE_USER_DATA = 'CHATS_CHANGE_USER_DATA'
export const CHATS_CHANGE_CHAT_DATA = 'CHATS_CHANGE_CHAT_DATA'
export const CHATS_CHANGE_SELECTED_CHAT = 'CHATS_CHANGE_SELECTED_CHAT'
export const CHATS_ADD_MESSAGE_FOR_CHAT = 'CHATS_ADD_MESSAGE_FOR_CHAT'